Repository vshn/appcat-comp-functions, pull requests merged in 2023-05, with the labels that each got.

#33 Add generated stackgres structs for SGDbOps and SGCluster
  Makefile
  Makefile.vars.mk
  apis/stackgres/v1/.gitignore
  apis/stackgres/v1/groupversion_info.go
  apis/stackgres/v1/sgcluster.gen.go
  apis/stackgres/v1/sgcluster.go
  apis/stackgres/v1/sgcluster.yaml
  apis/stackgres/v1/sgdbops.gen.go
  apis/stackgres/v1/sgdbops.go
  apis/stackgres/v1/sgdbops.yaml
  apis/stackgres/v1/zz_generated.deepcopy.go
  go.mod
  go.sum
  tools.go
Labels: change

#23 Add UpdateStrategy to VSHNPostgreSQL
  functions/vshn-postgres-func/restart.go
  functions/vshn-postgres-func/restart_test.go
  go.mod
  go.sum
  main.go
  test/transforms/vshn-postgres/restart/01-NoPendingReboot.yaml
  test/transforms/vshn-postgres/restart/02-PendingReboot.yaml
  test/transforms/vshn-postgres/restart/02-PendingRebootNoRestart.yaml
  test/transforms/vshn-postgres/restart/03-KeepRecentReboots.yaml
Labels: enhancement

#34 Patch SgCluster object via composition function
  functions/vshn-postgres-func/encrypted_pvc.go
  functions/vshn-postgres-func/encrypted_pvc_test.go
  functions/vshn-postgres-func/utils.go
  main.go
  runtime/desired.go
  runtime/observed.go
  runtime/run.go
  runtime/runtime.go
  test/transforms/vshn-postgres/enc_pvc/03-GivenEncryptionParams.yaml
  test/transforms/vshn-postgres/enc_pvc/03-GivenEncryptionParamsExistingSecret.yaml
  test/transforms/vshn-postgres/enc_pvc/03-GivenEncryptionParamsNoInstanceNamespace.yaml
Labels: bug

#35 Deprecate repo
  README.md
Labels: dependency
