Repository vshn/appcat-comp-functions, pull requests merged in 2023-04, with the labels that each got.

#12 Fix resource get function
  runtime/run.go
  runtime/runtime.go
Labels: bug

#5 Add/user alerting
  Dockerfile
  functions/vshn-postgres-func/alerting.go
  functions/vshn-postgres-func/alerting_test.go
  functions/vshn-postgres-func/common_test.go
  functions/vshn-postgres-func/url.go
  functions/vshn-postgres-func/url_test.go
  go.mod
  go.sum
  main.go
  runtime/runtime.go
  test/example.yaml
  test/transforms/vshn-postgres/alerting/01-GivenNoMonitoringParams.yaml
  test/transforms/vshn-postgres/alerting/01-ThenExpectNoOutput.yaml
  test/transforms/vshn-postgres/alerting/02-GivenConfigRefNoSecretRef.yaml
  test/transforms/vshn-postgres/alerting/02-ThenExpectError.yaml
  test/transforms/vshn-postgres/alerting/03-GivenConfigRefAndSecret.yaml
  test/transforms/vshn-postgres/alerting/04-GivenConfigTemplateAndSecret.yaml
Labels: enhancement

#17 Pass the specified name to the target secret
  functions/vshn-postgres-func/alerting.go
  functions/vshn-postgres-func/alerting_test.go
Labels: bug

#19 Improve runtime library
  README.md
  docs/antora-preview.mk
  docs/antora.yml
  docs/modules/ROOT/nav.adoc
  docs/modules/ROOT/pages/explanations/runtime.adoc
  docs/modules/ROOT/pages/explanations/vshn-postgres.adoc
  docs/modules/ROOT/pages/index.adoc
  functions/vshn-postgres-func/alerting.go
  functions/vshn-postgres-func/alerting_test.go
  functions/vshn-postgres-func/app.go
  functions/vshn-postgres-func/common_test.go
  functions/vshn-postgres-func/url.go
  functions/vshn-postgres-func/url_test.go
  main.go
  runtime/desired.go
  runtime/observed.go
  runtime/result.go
  runtime/run.go
  runtime/runtime.go
  runtime/types.go
  test/example.yaml
Labels: enhancement

#20 Add randomized defaults for maintenance and backup of VSHNPostgresql
  functions/vshn-postgres-func/schedule.go
  functions/vshn-postgres-func/schedule_test.go
  go.mod
  main.go
  test/transforms/vshn-postgres/base.yaml
Labels: enhancement

#25 Improve result message
  runtime/run.go
Labels: enhancement

#24 replacing CLI with gRPC server
  Dockerfile
  functions/vshn-postgres-func/app.go
  functions/vshn-postgres-func/common_test.go
  go.mod
  go.sum
  main.go
  runtime/logger.go
  runtime/run.go
  runtime/runtime.go
  test/grpc-client/main.go
Labels: enhancement

#29 updating dependencies (component-appcat)
  go.mod
  go.sum
Labels: dependency

#21 Add function for encrypted pvc
  functions/vshn-postgres-func/encrypted_pvc.go
  functions/vshn-postgres-func/encrypted_pvc_test.go
  go.mod
  go.sum
  main.go
  test/example.yaml
  test/transforms/vshn-postgres/enc_pvc/01-GivenNoEncryptionParams.yaml
  test/transforms/vshn-postgres/enc_pvc/01-ThenExpectNoOutput.yaml
  test/transforms/vshn-postgres/enc_pvc/02-GivenEncryptionParamsFalse.yaml
  test/transforms/vshn-postgres/enc_pvc/02-ThenExpectFalseOutput.yaml
  test/transforms/vshn-postgres/enc_pvc/03-GivenEncryptionParams.yaml
  test/transforms/vshn-postgres/enc_pvc/03-GivenEncryptionParamsExistingSecret.yaml
  test/transforms/vshn-postgres/enc_pvc/03-GivenEncryptionParamsNoInstanceNamespace.yaml
Labels: enhancement

#31 Disable gh-pages as we don't use them
  .github/workflows/docs.yml
Labels: documentation
